name: CI Pipeline for Credit Risk App

# when does it work ? (when code came main branch)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. pull the code from githup
    - uses: actions/checkout@v3

    # 2.set  Python 3.11 
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3. install library (it is neccessary for httpx test)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx pytest

    # 4. run test
    - name: Run Tests with Pytest
      run: |
        pytest